### PR TITLE
Logan W change

### PR DESCRIPTION
**Pull request by DisarmedRemo66**
Made a change.

### CODE REVIEW

**Comment by bjones1** [comment]
Logan, it looks like you've started on this assignment, but are missing important pieces. How can I help?

**Comment by bjones1** [comment]
Never mind -- I see you submitted #12.

**Comment by DisarmedRemo66** [comment]
Good evening Dr. Jones,

Thank you for the feedback and the extended time to fix my mistakes, I'll
be working on this assignment later tonight and hopefully have it completed
by tomorrow. I'll make sure to have some good questions for tomorrow
regarding smartGit.

Regards,
Logan Williams
***@***.***

**Comment by bjones1** [comment]
Sounds good!

**Pull request closed without merging**
