### PR TITLE
Omc56 updated with suggestions

### PR DESCRIPTION
**Pull request by Starnol**
Okay I think I have it working.

### CODE REVIEW

**Comment by Starnol** [comment]
I will be adding JP comment file and try to get it in the correct order to show the story. Then merge them and hopefully be able to send another pull request.

**Comment by bjones1** [comment]
I left a lot of comments on #23 -- did you see those? I don't understand what this PR is.

**Comment by bjones1** [comment]
Close all PRs that are old -- is this the current one, or should it be closed?

**Comment by Starnol** [comment]
Smart git wouldn't let me do a pull request until a couple of days ago so i am not sure how these are on here.

**Pull request closed without merging**
